# Run eslint

name: ESLint

on:
    push:
        branches: ['*'] # Run on each push
        branches-ignore: [main, dev] # Ignore 'dev' and 'main', just run it on feature branches
    pull_request:
        branches: [main, dev]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
            - name: Install dependencies
              run: npm ci
            - name: Run ESLint
              run: npm run lint
