# Run eslint

name: ESLint

on:
    pull_request:
        branches: [main, dev]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '22'
            - name: Install dependencies
              run: npm ci
            - name: Run ESLint
              run: npm run lint
